[phases.setup]
nixPkgs = ['...', 'chromium']

[phases.install]
cmds = ['npm ci --omit=dev']

[start]
cmd = 'npm start'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = '1'
PUPPETEER_EXECUTABLE_PATH = '/nix/store/chromium/bin/chromium'
NODE_ENV = 'production'